export const SITE_CONFIG = {
    baseUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://fineksi.com',
    name: process.env.NEXT_PUBLIC_SITE_NAME || 'Fineksi',
    description: process.env.NEXT_PUBLIC_SITE_DESCRIPTION || 'AI-powered cognitive document automation and credit analysis for financial institutions',
    siteTitle: process.env.NEXT_PUBLIC_SITE_TITLE || 'Fineksi - AI-Powered Cognitive Document Automation for Financial Institutions',
    siteDescription: process.env.NEXT_PUBLIC_SITE_META_DESCRIPTION || 'Transform your credit process with advanced AI cognitive document automation, fraud detection, and credit analysis with high speed and accuracy. Trusted by banks, multifinance, and P2P lending platforms.',
    email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'support@fineksi.com',
    phone: process.env.NEXT_PUBLIC_CONTACT_PHONE || '+62 851 5907 9011',
    idLegalEntity: process.env.NEXT_PUBLIC_ID_LEGAL_ENTITY || 'PT Finskor Teknologi Indonesia',
    sgLegalEntity: process.env.NEXT_PUBLIC_SG_LEGAL_ENTITY || 'Fineksi Pte Ltd',
    idAddress: process.env.NEXT_PUBLIC_ID_ADDRESS || 'Gedung AD Premier Office Park Lantai 9, Jalan TB Simatupang No.5, Kelurahan Ragunan, Kecamatan Pasar Minggu, Jakarta Selatan',
    sgAddress: process.env.NEXT_PUBLIC_SG_ADDRESS || '160 Robinson Road #14-04, Singapore 068914',
    linkedinLink: process.env.NEXT_PUBLIC_LINKEDIN_URL || 'https://linkedin.com/company/finskor',
    twitterLink: process.env.NEXT_PUBLIC_TWITTER_URL || 'https://twitter.com/fineksiofficial',
    instagramLink: process.env.NEXT_PUBLIC_INSTAGRAM_URL || 'https://www.instagram.com/fineksi.official/',
    blogLink: process.env.NEXT_PUBLIC_BLOG_URL || 'https://blog.fineksi.com',
    industry: process.env.NEXT_PUBLIC_INDUSTRY || 'Information Technology',
    foundingYear: process.env.NEXT_PUBLIC_FOUNDING_YEAR || '2024',
    gaTrackingId: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || ''
} as const